In [1]:
import pandas as pd
import os

os.environ["YDATA_LICENSE_KEY"] = "2663947a-1f91-4b5b-b37a-0fe8fb31a310"

In [2]:
df = pd.read_csv('../data/preprocessed/preprocessed_1.csv')
data = df.reset_index()
print(data.shape)
data

(2975, 53)

,index,match_api_id,season,stage,date,away_team,home_team,result_match,points_home,points_away,...,rolling_avg_shoton_diff,rolling_stability_shoton_diff,points_diff,rolling_avg_goals_ratio,rolling_stability_goal_ratio,rolling_avg_goals_conversion_rate_ratio,rolling_stability_goals_conversion_rate_ratio,rolling_avg_shoton_ratio,rolling_stability_shoton_ratio,points_ratio
0,0,489063,2008/2009,3,2008-08-30,10261,9825,1,3,4,...,11.000,0.000000,-1,1.000000,0.000000,0.083333,0.000000,12.000000,0.000000,0.750000
1,1,489068,2008/2009,3,2008-08-30,10194,8549,1,3,3,...,6.000,0.000000,0,0.333333,0.000000,0.047619,0.000000,7.000000,0.000000,1.000000
2,2,489069,2008/2009,3,2008-08-30,8659,8559,0,3,0,...,3.000,0.000000,3,3.000000,0.000000,1.200000,0.000000,2.500000,0.000000,0.000000
3,3,489070,2008/2009,3,2008-08-30,8528,8667,0,4,0,...,-2.000,0.000000,4,1.000000,0.000000,1.400000,0.000000,0.714286,0.000000,0.000000
4,4,489066,2008/2009,3,2008-08-31,8650,10252,0,3,6,...,-6.000,0.000000,-3,1.000000,0.000000,2.200000,0.000000,0.454545,0.000000,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2970,1987599,2015/2016,38,2016-05-15,9850,8668,1,44,34,...,1.750,1.997741,10,0.787234,0.664167,0.906304,2.427300,1.360825,1.830911,1.294118
2971,2971,1987598,2015/2016,38,2016-05-15,8197,8455,0,49,80,...,-0.225,-0.287583,-31,1.240741,0.998262,1.187056,0.745876,0.963265,0.878481,0.612500
2972,2972,1987597,2015/2016,38,2016-05-15,10252,9825,1,68,17,...,2.250,0.163344,51,1.576923,2.228928,0.735651,0.502278,1.428571,1.055619,4.000000
2973,2973,1987601,2015/2016,38,2016-05-15,8586,10261,1,34,70,...,-3.000,-1.216450,-36,0.702381,0.695592,1.436965,2.007396,0.610390,0.664192,0.485714
2974,2974,1987600,2015/2016,38,2016-05-17,8678,10260,1,63,42,...,0.475,2.273465,21,0.663793,0.477157,0.788829,0.906174,1.076305,1.968858,1.500000

In [3]:
from ydata.dataset import Dataset
from ydata.synthesizers.regular import RegularSynthesizer
from ydata_synthetic.synthesizers.base import ModelParameters, TrainParameters
from ydata.metadata import Metadata

# Wrap the DataFrame in a Dataset object
dataset = Dataset(data)

dataset_attrs = {
    "sortbykey": "date",
}

# Create metadata from the Dataset
metadata = Metadata(dataset, dataset_attrs=dataset_attrs)

# Specify numerical and categorical columns
num_cols = data.select_dtypes(include='number').columns.tolist()
cat_cols = data.select_dtypes(exclude='number').columns.tolist()

# Define model parameters
model_params = ModelParameters(batch_size=500, lr=2e-4, betas=(0.5, 0.9))

# Initialize the synthesizer
synthesizer = RegularSynthesizer()

# Train the synthesizer on the data
synthesizer.fit(X=dataset, metadata=metadata)

# Generate synthetic samples
synthetic_data = synthesizer.sample(1000)
synthetic_data.head()

[########################################] | 100% Completed | 102.55 ms
[########################################] | 100% Completed | 415.34 ms
[########################################] | 100% Completed | 101.24 ms
[########################################] | 100% Completed | 403.43 ms
INFO: 2025-03-21 23:41:33,894 Pandas backend loaded 2.2.3
INFO: 2025-03-21 23:41:33,897 Numpy backend loaded 1.26.4
INFO: 2025-03-21 23:41:33,897 Pyspark backend NOT loaded
INFO: 2025-03-21 23:41:33,898 Python backend loaded
Validate the segmentation strategy.
INFO: 2025-03-21 23:41:34,317 [SYNTHESIZER] - Number columns considered for synth: 53
INFO: 2025-03-21 23:41:35,039 [SYNTHESIZER] - Starting the synthetic data modeling process over 1x1 blocks.
INFO: 2025-03-21 23:41:35,043 [SYNTHESIZER] - Preprocess segment
INFO: 2025-03-21 23:41:35,047 [SYNTHESIZER] - Synthesizer init.
INFO: 2025-03-21 23:41:35,048 [SYNTHESIZER] - Processing the data prior fitting the synthesizer.
INFO: 2025-03-21 23:41:38,804 [SYNTHESIZER] - Start generating model samples.
INFO: 2025-03-21 23:41:38,804 [SYNTHESIZER] - Init Dask cluster for sampling.
INFO: 2025-03-21 23:41:38,813 To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
INFO: 2025-03-21 23:41:38,815 State start
INFO: 2025-03-21 23:41:38,816 Found stale lock file and directory '/tmp/dask-scratch-space/scheduler-ro01m120', purging
INFO: 2025-03-21 23:41:38,819   Scheduler at:     tcp://127.0.0.1:33579
INFO: 2025-03-21 23:41:38,819   dashboard at:  http://127.0.0.1:8787/status
INFO: 2025-03-21 23:41:38,819 Registering Worker plugin shuffle
INFO: 2025-03-21 23:41:38,831         Start Nanny at: 'tcp://127.0.0.1:35007'
INFO: 2025-03-21 23:41:38,834         Start Nanny at: 'tcp://127.0.0.1:39329'
INFO: 2025-03-21 23:41:38,835         Start Nanny at: 'tcp://127.0.0.1:36059'
INFO: 2025-03-21 23:41:38,855         Start Nanny at: 'tcp://127.0.0.1:34529'
INFO: 2025-03-21 23:41:38,858         Start Nanny at: 'tcp://127.0.0.1:35397'
INFO: 2025-03-21 23:41:38,859         Start Nanny at: 'tcp://127.0.0.1:39817'
INFO: 2025-03-21 23:41:39,274 Register worker addr: tcp://127.0.0.1:33313 name: 0
INFO: 2025-03-21 23:41:39,275 Starting worker compute stream, tcp://127.0.0.1:33313
INFO: 2025-03-21 23:41:39,275 Starting established connection to tcp://127.0.0.1:53352
INFO: 2025-03-21 23:41:39,300 Register worker addr: tcp://127.0.0.1:37443 name: 5
INFO: 2025-03-21 23:41:39,301 Starting worker compute stream, tcp://127.0.0.1:37443
INFO: 2025-03-21 23:41:39,301 Starting established connection to tcp://127.0.0.1:53354
INFO: 2025-03-21 23:41:39,302 Register worker addr: tcp://127.0.0.1:45055 name: 4
INFO: 2025-03-21 23:41:39,303 Starting worker compute stream, tcp://127.0.0.1:45055
INFO: 2025-03-21 23:41:39,303 Starting established connection to tcp://127.0.0.1:53376
INFO: 2025-03-21 23:41:39,303 Register worker addr: tcp://127.0.0.1:46711 name: 3
INFO: 2025-03-21 23:41:39,304 Starting worker compute stream, tcp://127.0.0.1:46711
INFO: 2025-03-21 23:41:39,304 Starting established connection to tcp://127.0.0.1:53368
INFO: 2025-03-21 23:41:39,309 Register worker addr: tcp://127.0.0.1:39257 name: 1
INFO: 2025-03-21 23:41:39,310 Starting worker compute stream, tcp://127.0.0.1:39257
INFO: 2025-03-21 23:41:39,310 Starting established connection to tcp://127.0.0.1:53378
INFO: 2025-03-21 23:41:39,323 Register worker addr: tcp://127.0.0.1:33161 name: 2
INFO: 2025-03-21 23:41:39,324 Starting worker compute stream, tcp://127.0.0.1:33161
INFO: 2025-03-21 23:41:39,324 Starting established connection to tcp://127.0.0.1:53384
INFO: 2025-03-21 23:41:39,373 Receive client connection: Client-a6e797d3-06a5-11f0-ba34-1b684611e79a
INFO: 2025-03-21 23:41:39,373 Starting established connection to tcp://127.0.0.1:53398
INFO: 2025-03-21 23:41:40,465 [SYNTHESIZER] - Postprocessing.
INFO: 2025-03-21 23:41:40,473 [SYNTHESIZER] - Numerical clipping

/home/kamil/PycharmProjects/predict_football_results/.venv/lib/python3.12/site-packages/dask/dataframe/__init__.py:49: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

INFO: 2025-03-21 23:41:41,470 let write into the connector None
INFO: 2025-03-21 23:41:41,471 using kwargs {}

/home/kamil/PycharmProjects/predict_football_results/.venv/lib/python3.12/site-packages/dask/dataframe/__init__.py:49: FutureWarning:
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)

,index,match_api_id,season,stage,date,away_team,home_team,result_match,points_home,points_away,...,rolling_avg_shoton_diff,rolling_stability_shoton_diff,points_diff,rolling_avg_goals_ratio,rolling_stability_goal_ratio,rolling_avg_goals_conversion_rate_ratio,rolling_stability_goals_conversion_rate_ratio,rolling_avg_shoton_ratio,rolling_stability_shoton_ratio,points_ratio
0,1093,840216,2010/2011,37,2011-05-15,8586,8650,0,62,77,...,2.100,-0.329492,-18,1.891892,1.897367,1.799690,4.491068,1.411765,0.890763,0.783133
1,1875,1474165,2013/2014,3,2013-08-31,8472,9826,1,0,1,...,-2.300,-1.423261,0,1.371134,0.653491,1.859406,1.784221,0.634921,0.593465,1.000000
2,2122,1474998,2013/2014,28,2014-03-01,8455,9850,0,33,60,...,-1.900,-1.695356,-30,0.985294,0.341861,0.694629,0.511972,0.769231,0.657347,0.523810
3,1540,1229169,2012/2013,7,2012-10-06,8668,8456,0,4,13,...,-3.000,-3.712978,-7,1.283951,1.630730,2.542576,6.635410,0.615385,0.365491,0.384615
4,2103,1474968,2013/2014,27,2014-02-22,8668,8344,0,22,21,...,1.225,2.026651,-5,0.738462,0.400195,0.825901,0.702267,1.307692,2.372806,0.807692

In [6]:
import ydata

if isinstance(synthetic_data, ydata.dataset.dataset.Dataset):
    synthetic_data = synthetic_data.to_pandas()

X = pd.concat([synthetic_data, data])
X = X.drop(["match_api_id", "index"], axis="columns")
y = [0] * len(synthetic_data) + [1] * len(data)

In [7]:
X

,season,stage,date,away_team,home_team,result_match,points_home,points_away,home_last_team_goal,home_last_team_shoton,...,rolling_avg_shoton_diff,rolling_stability_shoton_diff,points_diff,rolling_avg_goals_ratio,rolling_stability_goal_ratio,rolling_avg_goals_conversion_rate_ratio,rolling_stability_goals_conversion_rate_ratio,rolling_avg_shoton_ratio,rolling_stability_shoton_ratio,points_ratio
0,2010/2011,37,2011-05-15,8586,8650,0,62,77,2.000000,4.0,...,2.100,-0.329492,-18,1.891892,1.897367,1.799690,4.491068,1.411765,0.890763,0.783133
1,2013/2014,3,2013-08-31,8472,9826,1,0,1,1.000000,4.0,...,-2.300,-1.423261,0,1.371134,0.653491,1.859406,1.784221,0.634921,0.593465,1.000000
2,2013/2014,28,2014-03-01,8455,9850,0,33,60,2.000000,6.0,...,-1.900,-1.695356,-30,0.985294,0.341861,0.694629,0.511972,0.769231,0.657347,0.523810
3,2012/2013,7,2012-10-06,8668,8456,0,4,13,2.333333,4.0,...,-3.000,-3.712978,-7,1.283951,1.630730,2.542576,6.635410,0.615385,0.365491,0.384615
4,2013/2014,27,2014-02-22,8668,8344,0,22,21,1.000000,4.0,...,1.225,2.026651,-5,0.738462,0.400195,0.825901,0.702267,1.307692,2.372806,0.807692
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,2015/2016,38,2016-05-15,9850,8668,1,44,34,1.000000,4.0,...,1.750,1.997741,10,0.787234,0.664167,0.906304,2.427300,1.360825,1.830911,1.294118
2971,2015/2016,38,2016-05-15,8197,8455,0,49,80,2.000000,5.0,...,-0.225,-0.287583,-31,1.240741,0.998262,1.187056,0.745876,0.963265,0.878481,0.612500
2972,2015/2016,38,2016-05-15,10252,9825,1,68,17,2.000000,7.0,...,2.250,0.163344,51,1.576923,2.228928,0.735651,0.502278,1.428571,1.055619,4.000000
2973,2015/2016,38,2016-05-15,8586,10261,1,34,70,1.750000,6.0,...,-3.000,-1.216450,-36,0.702381,0.695592,1.436965,2.007396,0.610390,0.664192,0.485714
2974,2015/2016,38,2016-05-17,8678,10260,1,63,42,1.000000,17.0,...,0.475,2.273465,21,0.663793,0.477157,0.788829,0.906174,1.076305,1.968858,1.500000

In [8]:
# Adversarial validation

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import roc_auc_score


model = RandomForestClassifier()

feature_cols = [col for col in X.columns if col not in
                    ["match_api_id", "result_match", "season", "stage", "date", "home_team", "away_team"]]

X = X[feature_cols]

cv_preds = cross_val_predict(model, X, y, cv=5, n_jobs=-1, method="predict_proba")
roc_adv_score = roc_auc_score(y_true=y, y_score=cv_preds[:, 1])
print(f"roc auc adv score: {roc_adv_score:0.3f}")

roc auc adv score: 0.462