In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
raw_df_match_details = pd.read_csv('../data/raw/match_details.csv')
raw_df_player_attr = pd.read_csv('../data/raw/player_attributes.csv')

In [3]:
raw_df_player_attr

,id,player_fifa_api_id,player_api_id,date,overall_rating,potential,preferred_foot,attacking_work_rate,defensive_work_rate,crossing,...,vision,penalties,marking,standing_tackle,sliding_tackle,gk_diving,gk_handling,gk_kicking,gk_positioning,gk_reflexes
0,1,218353,505942,2016-02-18 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
1,2,218353,505942,2015-11-19 00:00:00,67.0,71.0,right,medium,medium,49.0,...,54.0,48.0,65.0,69.0,69.0,6.0,11.0,10.0,8.0,8.0
2,3,218353,505942,2015-09-21 00:00:00,62.0,66.0,right,medium,medium,49.0,...,54.0,48.0,65.0,66.0,69.0,6.0,11.0,10.0,8.0,8.0
3,4,218353,505942,2015-03-20 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
4,5,218353,505942,2007-02-22 00:00:00,61.0,65.0,right,medium,medium,48.0,...,53.0,47.0,62.0,63.0,66.0,5.0,10.0,9.0,7.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183973,183974,102359,39902,2009-08-30 00:00:00,83.0,85.0,right,medium,low,84.0,...,88.0,83.0,22.0,31.0,30.0,9.0,20.0,84.0,20.0,20.0
183974,183975,102359,39902,2009-02-22 00:00:00,78.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183975,183976,102359,39902,2008-08-30 00:00:00,77.0,80.0,right,medium,low,74.0,...,88.0,70.0,32.0,31.0,30.0,9.0,20.0,73.0,20.0,20.0
183976,183977,102359,39902,2007-08-30 00:00:00,78.0,81.0,right,medium,low,74.0,...,88.0,53.0,28.0,32.0,30.0,9.0,20.0,73.0,20.0,20.0
183977,183978,102359,39902,2007-02-22 00:00:00,80.0,81.0,right,medium,low,74.0,...,88.0,53.0,38.0,32.0,30.0,9.0,9.0,78.0,7.0,15.0

In [4]:
# raw_df_match_details.info()

In [5]:
# raw_df_player_attr.info()

In [6]:
raw_df_match_details['date'] = pd.to_datetime(raw_df_match_details['date'])
raw_df_player_attr['date'] = pd.to_datetime(raw_df_player_attr['date'])
raw_df_match_details.sort_values(by=['season', 'date'], inplace=True)

In [7]:
def get_points(row, team):
    points_mapping = {
        'H': {'home': 3, 'away': 0},
        'D': {'home': 1, 'away': 1},
        'A': {'home': 0, 'away': 3}
    }
    team_type = 'home' if row['home_team'] == team else 'away'
    return int(points_mapping[row['result_match']][team_type])


def process_points(team, df, match_date, match_season):
    team_matches = df.query(
        '(home_team == @team | away_team == @team) & (season == @match_season & date < @match_date)')
    if len(team_matches) == 0:
        return 0

    return team_matches.apply(lambda row: get_points(row, team), axis=1).sum()


def count_points(match_row, df):
    match_date = match_row['date']
    match_season = match_row['season']
    home_team = match_row['home_team']
    away_team = match_row['away_team']

    home_team_points = process_points(home_team, df, match_date, match_season)
    away_team_points = process_points(away_team, df, match_date, match_season)

    return home_team_points, away_team_points


raw_df_match_details[['points_home', 'points_away']] = raw_df_match_details.apply(
    lambda row: count_points(row, raw_df_match_details), axis=1, result_type='expand')

In [8]:
raw_df_match_details['result_match']

0       H
1       A
2       H
3       A
4       H
       ..
3035    H
3036    D
3037    D
3038    D
3039    H
Name: result_match, Length: 3040, dtype: object

In [9]:
raw_df_match_details = (raw_df_match_details
                        .assign(date=pd.to_datetime(raw_df_match_details['date']),
                                result_match=lambda df: (df['result_match'] == 'H').astype(int))
                        )

In [10]:
from playerstats import player_stats

players_cols = ['{}_player_{}'.format(team, i) for team in ['home', 'away'] for i in range(1, 12)]

player_stats_dict_series = raw_df_match_details.apply(
    lambda row: player_stats.get_player_stat(
        match_row=row,
        df_matches=raw_df_match_details,
        df_player_attr=raw_df_player_attr,
        players=players_cols
    ),
    axis=1
)

new_player_stats_df = pd.json_normalize(player_stats_dict_series)

df = pd.merge(raw_df_match_details, new_player_stats_df, how='left', on='match_api_id')
df.drop(players_cols, axis=1, inplace=True)
matching_columns = ([col for col in df.columns if 'player_rating' in col] +
                    [col for col in df.columns if 'aggression_rating' in col] +
                    [col for col in df.columns if 'strength_rating' in col] +
                    [col for col in df.columns if 'acceleration_rating' in col])

df.dropna(subset=matching_columns, inplace=True)
# matching_columns_filtered = [c for c in df.columns if c != "date" and c != "season"]

In [11]:
df

,match_api_id,season,stage,date,away_team,home_team,home_team_goal,away_team_goal,result_match,away_shoton,...,strength_rating_away_player_9,aggression_rating_away_player_9,overall_rating_away_player_10,acceleration_rating_away_player_10,strength_rating_away_player_10,aggression_rating_away_player_10,overall_rating_away_player_11,acceleration_rating_away_player_11,strength_rating_away_player_11,aggression_rating_away_player_11
0,489043,2008/2009,1,2008-08-16,8659,9825,1,0,1,0,...,56.0,70.0,73.000000,77.000000,67.000000,64.000000,68.0,81.0,80.0,66.0
1,489044,2008/2009,1,2008-08-16,8650,8472,0,1,0,0,...,39.0,40.5,85.000000,83.500000,65.500000,39.500000,87.0,90.0,75.5,71.0
2,489045,2008/2009,1,2008-08-16,8528,8654,2,1,1,0,...,75.5,62.0,71.000000,77.000000,77.000000,59.000000,75.0,75.0,91.5,77.0
3,489047,2008/2009,1,2008-08-16,8655,8668,2,3,0,0,...,75.5,76.0,76.000000,81.000000,91.000000,81.000000,80.0,77.0,79.0,72.0
4,489048,2008/2009,1,2008-08-16,8586,8549,2,1,1,0,...,69.0,48.0,72.500000,88.500000,61.500000,53.500000,83.5,90.0,73.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,1987603,2015/2016,38,2016-05-15,8654,10194,2,1,1,6,...,37.7,24.6,73.900000,76.800000,75.500000,62.200000,77.4,69.0,92.0,83.2
3036,1987604,2015/2016,38,2016-05-15,8456,10003,1,1,0,2,...,74.3,55.1,69.444444,86.666667,70.777778,53.333333,87.3,92.0,70.9,57.0
3037,1987605,2015/2016,38,2016-05-15,8472,9817,2,2,0,8,...,53.2,41.1,72.200000,51.000000,66.500000,81.100000,77.7,75.3,84.4,76.1
3038,1987606,2015/2016,38,2016-05-15,8650,8659,1,1,0,17,...,91.3,77.7,62.400000,80.900000,62.000000,39.600000,68.7,83.6,61.2,34.8
3039,1987600,2015/2016,38,2016-05-17,8678,10260,3,1,1,6,...,66.0,39.3,68.800000,91.800000,71.300000,72.200000,67.5,89.3,57.0,35.3

In [12]:
from src.shiftdata.shift_data import ShiftDataPreprocessor

preprocessor = ShiftDataPreprocessor(df)

home_df = preprocessor.select_and_rename_columns('home_')
away_df = preprocessor.select_and_rename_columns('away_')

team_df = preprocessor.concatenate_teams(home_df, away_df)

features_to_shift = ['team_goal', 'team_shoton', 'team_possession']
team_df_shifted = preprocessor.shift_features(features_to_shift)

df_final = preprocessor.merge_shifted_features(team_df_shifted)

df_final

INFO: Merging shifted features back into the original DataFrame.

,match_api_id,season,stage,date,away_team,home_team,result_match,points_home,points_away,overall_rating_home_player_1,...,overall_rating_away_player_11,acceleration_rating_away_player_11,strength_rating_away_player_11,aggression_rating_away_player_11,home_team_last_goal,home_team_last_shoton,home_team_last_possession,away_team_last_goal,away_team_last_shoton,away_team_last_possession
18,489063,2008/2009,3,2008-08-30,10261,9825,1,3,4,78.500000,...,76.500000,75.000000,81.000000,65.000000,1.00,12.0,34.0,1.0,1.0,55.0
21,489068,2008/2009,3,2008-08-30,10194,8549,1,3,3,73.500000,...,62.000000,72.500000,78.000000,61.000000,1.00,7.0,47.0,3.0,1.0,47.0
22,489069,2008/2009,3,2008-08-30,8659,8559,0,3,0,68.000000,...,68.000000,81.000000,80.000000,66.000000,3.00,5.0,53.0,1.0,2.0,66.0
23,489070,2008/2009,3,2008-08-30,8528,8667,0,4,0,65.500000,...,71.000000,77.000000,77.000000,59.000000,1.00,5.0,47.0,1.0,7.0,52.0
25,489066,2008/2009,3,2008-08-31,8650,10252,0,3,6,78.666667,...,87.333333,91.666667,75.666667,68.333333,2.00,5.0,48.0,2.0,11.0,46.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,1987603,2015/2016,38,2016-05-15,8654,10194,1,48,62,74.600000,...,77.400000,69.000000,92.000000,83.200000,1.00,4.0,47.0,1.0,1.0,46.0
3034,1987604,2015/2016,38,2016-05-15,8456,10003,0,46,65,75.400000,...,87.300000,92.000000,70.900000,57.000000,4.00,9.0,53.0,2.0,4.0,43.0
3035,1987605,2015/2016,38,2016-05-15,8472,9817,0,44,38,72.400000,...,77.700000,75.300000,84.400000,76.100000,1.75,8.0,35.0,3.0,6.0,53.0
3036,1987606,2015/2016,38,2016-05-15,8650,8659,0,42,59,77.800000,...,68.700000,83.600000,61.200000,34.800000,1.00,7.0,54.0,2.0,5.0,47.0
3037,1987600,2015/2016,38,2016-05-17,8678,10260,1,63,42,79.600000,...,67.500000,89.300000,57.000000,35.300000,1.00,17.0,33.0,1.0,6.0,56.0

In [13]:
df_ = df_final.copy()
df_.sort_values(['date'], inplace=True)

In [14]:
home_strength_rating_cols = df_.filter(like='strength_rating_home').columns.to_list()
away_strength_rating_cols = df_.filter(like='strength_rating_away').columns.to_list()

home_aggression_rating_cols = df_.filter(like='aggression_rating_home').columns.to_list()
away_aggression_rating_cols = df_.filter(like='aggression_rating_away').columns.to_list()

home_overall_rating_cols = df_.filter(like='overall_rating_home').columns.to_list()
away_overall_rating_cols = df_.filter(like='overall_rating_away').columns.to_list()

home_acceleration_rating_cols = df_.filter(like='acceleration_rating_home').columns.to_list()
away_acceleration_rating_cols = df_.filter(like='acceleration_rating_away').columns.to_list()

home_possession_rating_cols = df_.filter(like='home_team_last_possession').columns.to_list()
away_possession_rating_cols = df_.filter(like='away_team_last_possession').columns.to_list()

home_shoton_rating_cols = df_.filter(like='home_team_last_shoton').columns.to_list()
away_shoton_rating_cols = df_.filter(like='away_team_last_shoton').columns.to_list()

In [15]:
from helper import rolling_avg

df_['avg_team_strength_home'] = df_[home_strength_rating_cols].mean(axis=1)
df_['avg_team_strength_away'] = df_[away_strength_rating_cols].mean(axis=1)
df_['strength_difference'] = df_['avg_team_strength_home'] - df_['avg_team_strength_away']

df_['avg_team_aggression_home'] = df_[home_aggression_rating_cols].mean(axis=1)
df_['avg_team_aggression_away'] = df_[away_aggression_rating_cols].mean(axis=1)
df_['aggression_difference'] = df_['avg_team_aggression_home'] - df_['avg_team_aggression_away']

df_['avg_team_acceleration_home'] = df_[home_acceleration_rating_cols].mean(axis=1)
df_['avg_team_acceleration_away'] = df_[away_acceleration_rating_cols].mean(axis=1)
df_['acceleration_difference'] = df_['avg_team_acceleration_home'] - df_['avg_team_acceleration_away']

df_['goal_conversion_rate_home'] = np.where(
    df_['home_team_last_shoton'] <= 0,
    0,
    df_['home_team_last_goal'] / df_['home_team_last_shoton']
)

df_['goal_conversion_rate_away'] = np.where(
    df_['away_team_last_shoton'] <= 0,
    0,
    df_['away_team_last_goal'] / df_['away_team_last_shoton']
)

df_['home_team_strength_x_acceleration'] = df_['avg_team_acceleration_home'] * df_['avg_team_strength_home']
df_['away_team_strength_x_acceleration'] = df_['avg_team_acceleration_away'] * df_['avg_team_strength_away']

df_ = rolling_avg.calculate_rolling_avg_pandas(df_, 5)

columns_to_drop = (
        home_strength_rating_cols
        + away_strength_rating_cols
        + home_aggression_rating_cols
        + away_aggression_rating_cols
        + home_overall_rating_cols
        + away_overall_rating_cols
        + home_acceleration_rating_cols
        + away_acceleration_rating_cols
)

# Drop the valid columns
df_ = df_.drop(columns_to_drop, axis=1)

In [16]:
df_

,match_api_id,season,stage,date,away_team,home_team,result_match,points_home,points_away,home_team_last_goal,...,rolling_avg_goals_conversion_rate_home,rolling_stability_goals_conversion_rate_home,rolling_avg_shoton_home,rolling_stability_shoton_home,rolling_avg_goals_away,rolling_stability_goal_away,rolling_avg_goals_conversion_rate_away,rolling_stability_goals_conversion_rate_away,rolling_avg_shoton_away,rolling_stability_shoton_away
0,489063,2008/2009,3,2008-08-30,10261,9825,1,3,4,1.00,...,0.083333,NaN,12.000000,NaN,1.000000,NaN,1.000000,NaN,1.000000,NaN
1,489068,2008/2009,3,2008-08-30,10194,8549,1,3,3,1.00,...,0.142857,NaN,7.000000,NaN,3.000000,NaN,3.000000,NaN,1.000000,NaN
2,489069,2008/2009,3,2008-08-30,8659,8559,0,3,0,3.00,...,0.600000,NaN,5.000000,NaN,1.000000,NaN,0.500000,NaN,2.000000,NaN
3,489070,2008/2009,3,2008-08-30,8528,8667,0,4,0,1.00,...,0.200000,NaN,5.000000,NaN,1.000000,NaN,0.142857,NaN,7.000000,NaN
4,489066,2008/2009,3,2008-08-31,8650,10252,0,3,6,2.00,...,0.400000,NaN,5.000000,NaN,2.000000,NaN,0.181818,NaN,11.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,1987599,2015/2016,38,2016-05-15,9850,8668,1,44,34,1.00,...,0.630062,0.827042,4.629183,2.970881,3.293712,1.033570,0.558312,0.222770,6.379558,2.501802
2971,1987598,2015/2016,38,2016-05-15,8197,8455,0,49,80,2.00,...,0.456931,0.119539,5.326338,1.655867,2.295036,1.215420,0.471692,0.313761,5.728749,2.081047
2972,1987597,2015/2016,38,2016-05-15,10252,9825,1,68,17,2.00,...,0.278755,0.209993,8.341890,3.791857,1.601498,0.449658,0.813881,0.746699,4.519060,3.830061
2973,1987601,2015/2016,38,2016-05-15,8586,10261,1,34,70,1.75,...,0.607328,0.416387,4.061166,2.712356,1.767234,1.100003,0.278079,0.211140,6.528970,2.072934
2974,1987600,2015/2016,38,2016-05-17,8678,10260,1,63,42,1.00,...,0.181948,0.180485,10.690300,6.038343,1.269454,0.654729,0.220366,0.127416,6.303328,2.442912

In [17]:
df_['shot_efficiency_ratio_home'] = df_['rolling_stability_goal_home'] / (df_['rolling_stability_shoton_home'] + 1e-5)
df_['shot_efficiency_ratio_away'] = df_['rolling_stability_goal_away'] / (df_['rolling_stability_shoton_away'] + 1e-5)

# df_[['shot_efficiency_ratio_home', 'shot_efficiency_ratio_away']].describe().round(2)

In [18]:
df_[['rolling_stability_goal_home', 'rolling_stability_shoton_home', 'shot_efficiency_ratio_home']].loc[df_.shot_efficiency_ratio_home > 2.5].round(2)

,rolling_stability_goal_home,rolling_stability_shoton_home,shot_efficiency_ratio_home
13,1.41,0.0,141421.36
16,0.71,0.0,70710.68

In [19]:
df_[df_['shot_efficiency_ratio_home'] > 3].filter(like='efficiency')

    shot_efficiency_ratio_home  shot_efficiency_ratio_away
13               141421.356237                         NaN
16                70710.678119                    0.380056

In [20]:
df_[df_['shot_efficiency_ratio_home'] > 3].filter(like='rolling')

,rolling_avg_goals_home,rolling_stability_goal_home,rolling_avg_goals_conversion_rate_home,rolling_stability_goals_conversion_rate_home,rolling_avg_shoton_home,rolling_stability_shoton_home,rolling_avg_goals_away,rolling_stability_goal_away,rolling_avg_goals_conversion_rate_away,rolling_stability_goals_conversion_rate_away,rolling_avg_shoton_away,rolling_stability_shoton_away
13,1.8,1.414214,1.80,1.414214,1.0,0.0,2.000000,NaN,0.500000,NaN,4.000000,NaN
16,1.4,0.707107,0.35,0.176777,4.0,0.0,1.315789,0.584898,0.306391,0.171709,4.631579,1.538968

In [21]:
columns_to_compare = [
    ('rolling_avg_goals_home', 'rolling_avg_goals_away', 'rolling_avg_goals_diff'),
    ('rolling_stability_goal_home', 'rolling_stability_goal_away', 'rolling_stability_goal_diff'),
    ('rolling_avg_goals_conversion_rate_home', 'rolling_avg_goals_conversion_rate_away',
     'rolling_avg_goals_conversion_rate_diff'),
    ('rolling_stability_goals_conversion_rate_home', 'rolling_stability_goals_conversion_rate_away',
     'rolling_stability_goals_conversion_rate_diff'),
    ('rolling_avg_shoton_home', 'rolling_avg_shoton_away', 'rolling_avg_shoton_diff'),
    ('rolling_stability_shoton_home', 'rolling_stability_shoton_away', 'rolling_stability_shoton_diff'),
    ('points_home', 'points_away', 'points_diff'),
]

for home_col, away_col, diff_col in columns_to_compare:
    df_[diff_col] = df_[home_col] - df_[away_col]

In [22]:
df_

,match_api_id,season,stage,date,away_team,home_team,result_match,points_home,points_away,home_team_last_goal,...,rolling_stability_shoton_away,shot_efficiency_ratio_home,shot_efficiency_ratio_away,rolling_avg_goals_diff,rolling_stability_goal_diff,rolling_avg_goals_conversion_rate_diff,rolling_stability_goals_conversion_rate_diff,rolling_avg_shoton_diff,rolling_stability_shoton_diff,points_diff
0,489063,2008/2009,3,2008-08-30,10261,9825,1,3,4,1.00,...,NaN,NaN,NaN,0.000000,NaN,-0.916667,NaN,11.000000,NaN,-1
1,489068,2008/2009,3,2008-08-30,10194,8549,1,3,3,1.00,...,NaN,NaN,NaN,-2.000000,NaN,-2.857143,NaN,6.000000,NaN,0
2,489069,2008/2009,3,2008-08-30,8659,8559,0,3,0,3.00,...,NaN,NaN,NaN,2.000000,NaN,0.100000,NaN,3.000000,NaN,3
3,489070,2008/2009,3,2008-08-30,8528,8667,0,4,0,1.00,...,NaN,NaN,NaN,0.000000,NaN,0.057143,NaN,-2.000000,NaN,4
4,489066,2008/2009,3,2008-08-31,8650,10252,0,3,6,2.00,...,NaN,NaN,NaN,0.000000,NaN,0.218182,NaN,-6.000000,NaN,-3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2970,1987599,2015/2016,38,2016-05-15,9850,8668,1,44,34,1.00,...,2.501802,0.221394,0.413129,-1.877456,-0.375831,0.071750,0.604273,-1.750375,0.469080,10
2971,1987598,2015/2016,38,2016-05-15,8197,8455,0,49,80,2.00,...,2.081047,0.563487,0.584040,0.098747,-0.282355,-0.014761,-0.194222,-0.402411,-0.425180,-31
2972,1987597,2015/2016,38,2016-05-15,10252,9825,1,68,17,2.00,...,3.830061,0.228152,0.117402,0.296724,0.415464,-0.535126,-0.536706,3.822830,-0.038204,51
2973,1987601,2015/2016,38,2016-05-15,8586,10261,1,34,70,1.75,...,2.072934,0.249170,0.530648,-0.123565,-0.424164,0.329249,0.205247,-2.467804,0.639423,-36
2974,1987600,2015/2016,38,2016-05-17,8678,10260,1,63,42,1.00,...,2.442912,0.075481,0.268010,-0.055753,-0.198949,-0.038417,0.053069,4.386973,3.595431,21

In [23]:
df_.to_csv('../data/preprocessed/preprocessed_1.csv', index=False)

In [24]:
df_.columns.to_list()

['match_api_id',
 'season',
 'stage',
 'date',
 'away_team',
 'home_team',
 'result_match',
 'points_home',
 'points_away',
 'home_team_last_goal',
 'home_team_last_shoton',
 'home_team_last_possession',
 'away_team_last_goal',
 'away_team_last_shoton',
 'away_team_last_possession',
 'avg_team_strength_home',
 'avg_team_strength_away',
 'strength_difference',
 'avg_team_aggression_home',
 'avg_team_aggression_away',
 'aggression_difference',
 'avg_team_acceleration_home',
 'avg_team_acceleration_away',
 'acceleration_difference',
 'goal_conversion_rate_home',
 'goal_conversion_rate_away',
 'home_team_strength_x_acceleration',
 'away_team_strength_x_acceleration',
 'rolling_avg_goals_home',
 'rolling_stability_goal_home',
 'rolling_avg_goals_conversion_rate_home',
 'rolling_stability_goals_conversion_rate_home',
 'rolling_avg_shoton_home',
 'rolling_stability_shoton_home',
 'rolling_avg_goals_away',
 'rolling_stability_goal_away',
 'rolling_avg_goals_conversion_rate_away',
 'rolling_stability_goals_conversion_rate_away',
 'rolling_avg_shoton_away',
 'rolling_stability_shoton_away',
 'shot_efficiency_ratio_home',
 'shot_efficiency_ratio_away',
 'rolling_avg_goals_diff',
 'rolling_stability_goal_diff',
 'rolling_avg_goals_conversion_rate_diff',
 'rolling_stability_goals_conversion_rate_diff',
 'rolling_avg_shoton_diff',
 'rolling_stability_shoton_diff',
 'points_diff']